version: "3.9"

services:
  db:
    image: postgres
    container_name: octavius-db
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data/
      # ports:
      # - "5433:5432"
    env_file:
      - .env
    hostname: octavius
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  web:
    build: .
    command: sh docker_init.sh
    container_name: octavius-web
    volumes:
      - .:/octavius/src
      - octavius_static:/octavius/static
      - octavius_media:/octavius/media
    # ports:
    #   - "${EXPOSE_PORT:-8000}:8000"
    hostname: localhost
    env_file:
      - .env
    depends_on:
      - db
      - redis

    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: always
  nginx:
    image: nginx
    volumes:
      - octavius_static:/octavius/static
      - octavius_media:/octavius/media
      - ./infra/nginx:/etc/nginx/conf.d/
    links:
      - web:web
    depends_on:
      - web
      - db
    ports:
      - "${EXPOSE_PORT}:80"

volumes:
  postgres_db_volume:
  octavius_static:
  octavius_media:
