# Generated by Django 4.1.5 on 2023-01-13 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("requester", models.CharField(max_length=100)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("requested_fields", models.JSONField()),
                ("approved_data", models.JSONField(null=True)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
    ]
