# Generated by Django 4.1.5 on 2023-01-15 19:19

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("scan_to_share", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanrequest",
            name="request_id",
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22, unique=True
            ),
        ),
    ]
