# Generated by Django 4.1.5 on 2023-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan_to_share", "0002_alter_scanrequest_request_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scanrequest",
            old_name="request_time",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="scanrequest",
            name="approved_data",
        ),
        migrations.AddField(
            model_name="scanrequest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scanrequest",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
