# Generated by Django 4.1.5 on 2023-01-13 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region="NP"
            ),
        ),
    ]
