# Generated by Django 4.1.5 on 2023-01-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="mobile",
            new_name="mobile_number",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="mobile_verified",
            new_name="mobile_number_verified",
        ),
    ]
