# Generated by Django 4.1.5 on 2023-01-18 16:39

import autho.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autho", "0003_rename_mobile_user_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp",
            field=models.CharField(
                default=autho.models.generate_numeric_token, max_length=4
            ),
        ),
    ]
