# Generated by Django 4.1.5 on 2023-02-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activityhistory",
            old_name="fields",
            new_name="extra_info",
        ),
    ]
