# Generated by Django 4.1.5 on 2023-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_rename_fields_activityhistory_extra_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityhistory",
            name="activity",
            field=models.CharField(
                choices=[
                    ("logged_in", "Logged In"),
                    ("qr_generated", "Generated a QR Code"),
                    ("qr_scanned", "Scanned a QR Code"),
                    ("approved_access_request", "Approved Identity Access Request."),
                    ("viewed_shared_details", "Viewed Shared Identity Details"),
                ],
                max_length=100,
            ),
        ),
    ]
