# Generated by Django 4.1.5 on 2023-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr", "0003_identityaccesspermit_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizedrequester",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="authorized_requester_logo"
            ),
        ),
    ]
